application: wbor-hr
version: 1-5-alpha
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /
  script: main.app
- url: /index\.html
  script: main.app
- url: /static
  static_dir: static
- url: /dj.*
  script: dj.app
- url: /blog/.*/edit/?
  script: dj.app
- url: /.*
  script: main.app
- url: /stats.*
  script: google.appengine.ext.appstats.ui.app

libraries:
- name: django
  version: latest

admin_console:
  pages:
  - name: Appstats
    url: /stats