application: wbor-hr
version: 1-5-alpha
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
- url: /index\.html
  script: main.app
- url: /static
  static_dir: static
- url: /dj.*
  script: dj.app
- url: /blog/.*/edit/?
  script: dj.app
- url: /.*
  script: main.app

libraries:
- name: django
  version: latest
