application: wbor-hr
version: 1-5-alpha
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /
  script: main.app
- url: /index\.html
  script: main.app
- url: /static
  static_dir: static
- url: /favicon\.png
  static_files: static/images/favicon.png
  upload: static/images/favicon\.png
- url: /favicon\.ico
  static_files: static/images/favicon.png
  upload: static/images/favicon\.png
- url: /dj.*
  script: dj.app
- url: /blog/.*/edit/?
  script: dj.app
- url: /.*
  script: main.app

libraries:
- name: django
  version: latest
